---
- name: copy repository file
  template: src=mmilata-openshift.repo.j2 dest=/etc/yum.repos.d/mmilata-openshift.repo

- name: install openshift
  yum: name={{ item }} state=installed
  with_items:
  - openshift-master-{{ install_openshift_copr_version }}
  - openshift-node-{{ install_openshift_copr_version }}
